version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    container_name: "${APP_NAME}-php"
    volumes:
      - /Users/oscarramirez/Documents/dev/dermaplastic-main:/var/www/html/
    ports:
      - "${APP_PORT:-8080}:80"
volumes:
  documents:
    driver: local
networks:
  default:
    name: "dermaplastic"
