CREATE TABLE `llx_cfdimx_facture_carta_porte_transporte_maritimo` (
    `rowid` int(11) NOT NULL AUTO_INCREMENT,
    `entity` int(11) DEFAULT NULL,
    `facid` int(11) DEFAULT NULL,
    `permiso_sct` varchar(255) DEFAULT NULL,
    `num_permiso_sct` varchar(255) DEFAULT NULL,
    `nom_aseg` varchar(255) DEFAULT NULL,
    `num_poliza_seguro` varchar(255) DEFAULT NULL,
    `tipo_embarcacion` varchar(255) DEFAULT NULL,
    `matricula` varchar(255) DEFAULT NULL,
    `num_omi` varchar(255) DEFAULT NULL,
    `anio_embarcacion` varchar(255) DEFAULT NULL,
    `nombre_embarcacion` varchar(255) DEFAULT NULL,
    `nacionalidad_embarcacion` varchar(255) DEFAULT NULL,
    `unidades_arq_bruto` varchar(255) DEFAULT NULL,
    `tipo_carga` varchar(255) DEFAULT NULL,
    `numcert_itc` varchar(255) DEFAULT NULL,
    `eslora` varchar(255) DEFAULT NULL,
    `manga` varchar(255) DEFAULT NULL,
    `calado` varchar(255) DEFAULT NULL,
    `linea_naviera` varchar(255) DEFAULT NULL,
    `nom_agente_naviero` varchar(255) DEFAULT NULL,
    `num_aut_naviero` varchar(255) DEFAULT NULL,
    `num_viaje` varchar(255) DEFAULT NULL,
    `num_conoc_embarc` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`rowid`)
);