CREATE TABLE `llx_cfdimx_facture_carta_porte_figura_transporte` (
    `rowid` int(11) NOT NULL AUTO_INCREMENT,
    `entity` int(11) DEFAULT NULL,
    `facid` int(11) DEFAULT NULL,
    `numero` int(11) DEFAULT NULL,
    `tipo` varchar(255) DEFAULT NULL,
    `num_licencia` varchar(255) DEFAULT NULL,
    `rfc` varchar(255) DEFAULT NULL,
    `nombre` varchar(255) DEFAULT NULL,
    `numregidtrib` varchar(255) DEFAULT NULL,
    `parte_transporte` varchar(255) DEFAULT NULL,
    `residencia_fiscal` varchar(255) DEFAULT NULL,
    `calle` varchar(255) DEFAULT NULL,
    `num_ext` varchar(255) DEFAULT NULL,
    `num_int` varchar(255) DEFAULT NULL,
    `colonia` varchar(255) DEFAULT NULL,
    `localidad` varchar(255) DEFAULT NULL,
    `referencia` varchar(255) DEFAULT NULL,
    `cp` varchar(255) DEFAULT NULL,
    `municipio` varchar(255) DEFAULT NULL,
    `estado` varchar(255) DEFAULT NULL,
    `pais` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`rowid`)
);
