CREATE TABLE `llx_cfdimx_facture_carta_porte_direcciones` (
    `rowid` int(11) NOT NULL AUTO_INCREMENT,
    `entity` int(11) DEFAULT NULL,
    `facid` int(11) DEFAULT NULL,
    `num_dir` int(11) DEFAULT NULL,
    `tipo_estacion` varchar(255) DEFAULT NULL,
    `distancia_recorrida` varchar(255) DEFAULT NULL,    
    `fechahora` varchar(255) DEFAULT NULL,
    `id_ubicacion` varchar(255) DEFAULT NULL,
    `tipo_ubicacion` varchar(255) DEFAULT NULL,
    `nombre` varchar(255) DEFAULT NULL,
    `rfc` varchar(255) DEFAULT NULL,
    `numregidtrib` varchar(255) DEFAULT NULL,
    `residencia_fiscal` varchar(255) DEFAULT NULL,
    `num_estacion` varchar(255) DEFAULT NULL,
    `nom_estacion` varchar(255) DEFAULT NULL,
    `navegacion_trafico` varchar(255) DEFAULT NULL,
    `calle` varchar(255) DEFAULT NULL,
    `num_int` varchar(255) DEFAULT NULL,
    `num_ext` varchar(255) DEFAULT NULL,
    `colonia` varchar(255) DEFAULT NULL,
    `referencia` varchar(255) DEFAULT NULL,
    `cp` varchar(255) DEFAULT NULL,
    `localidad` varchar(255) DEFAULT NULL,
    `municipio` varchar(255) DEFAULT NULL,
    `estado` varchar(255) DEFAULT NULL,
    `pais` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`rowid`)
);