<?php
/* Copyright (C) 2005       Matthieu Valleton	<mv@seeschloss.org>
 * Copyright (C) 2006-2015  Laurent Destailleur  <eldy@users.sourceforge.net>
 * Copyright (C) 2007       Patrick Raguin		<patrick.raguin@gmail.com>
 * Copyright (C) 2005-2012  Regis Houssin		<regis.houssin@inodbox.com>
 * Copyright (C) 2015       Raphaël Doursenaud  <rdoursenaud@gpcsolutions.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *       \file       htdocs/categories/viewcat.php
 *       \ingroup    category
 *       \brief      Page to show a category card
 */

require '../main.inc.php';
require_once DOL_DOCUMENT_ROOT.'/categories/class/categorie.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/categories.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/class/extrafields.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/class/html.formother.class.php';
require_once DOL_DOCUMENT_ROOT . '/product/class/html.formproduct.class.php';
require_once DOL_DOCUMENT_ROOT . '/product/stock/class/productlot.class.php';

// Load translation files required by the page
$langs->load("categories");

$id         = GETPOST('id', 'int');
$label      = GETPOST('label', 'alpha');
$type       = GETPOST('type', 'aZ09');
$removeelem = GETPOST('removeelem', 'int');
$elemid     = GETPOST('elemid', 'int');

$action     = GETPOST('action', 'aZ09') ?GETPOST('action', 'aZ09') : 'view'; // The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = GETPOST('massaction', 'alpha'); // The bulk action (combo box choice into lists)
$show_files = GETPOST('show_files', 'int'); // Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm', 'alpha'); // Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha'); // We click on a Cancel button
$toselect   = GETPOST('toselect', 'array'); // Array of ids of elements selected into a list
$contextpage = GETPOST('contextpage', 'aZ') ?GETPOST('contextpage', 'aZ') : 'myobjectlist'; // To manage different context of search
$backtopage = GETPOST('backtopage', 'alpha'); // Go back to a dedicated page
$optioncss  = GETPOST('optioncss', 'aZ'); // Option for the css output (always '' except when 'print')

$date_lim_discount = GETPOST('date_lim_discount', 'alpha');
$date_lim_discountday = GETPOST('date_lim_discountday', 'int');
$date_lim_discountmonth = GETPOST('date_lim_discountmonth', 'int');
$date_lim_discountyear = GETPOST('date_lim_discountyear', 'int');

// Load variable for pagination
$limit = GETPOST('limit', 'int') ?GETPOST('limit', 'int') : $conf->liste_limit;
$sortfield = GETPOST('sortfield', 'alpha');
$sortorder = GETPOST('sortorder', 'alpha');
$page = GETPOST('page', 'int');
if (empty($page) || $page == -1 || GETPOST('button_search', 'alpha') || GETPOST('button_removefilter', 'alpha') || (empty($toselect) && $massaction === '0')) { $page = 0; }     // If $page is not defined, or '' or -1 or if we click on clear filters or if we select empty mass action
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;

$idwarehouse = -1;

if ($id == "" && $label == "")
{
	dol_print_error('', 'Missing parameter id');
	exit();
}

// Security check
$result = restrictedArea($user, 'categorie', $id, '&category');

$object = new Categorie($db);
$result = $object->fetch($id, $label);
if ($result <= 0) {
	dol_print_error($db, $object->error); exit;
}
$object->fetch_optionals();
if ($result <= 0) {
	dol_print_error($db, $object->error); exit;
}

$type = $object->type;
if (is_numeric($type)) $type = Categorie::$MAP_ID_TO_CODE[$type]; // For backward compatibility

$extrafields = new ExtraFields($db);
$extrafields->fetch_name_optionals_label($object->table_element);

// Initialize technical object to manage hooks. Note that conf->hooks_modules contains array array
$hookmanager->initHooks(array('categorycard', 'globalcard'));


/*
 *	Actions
 */
$parameters = array();
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action); // Note that $action and $object may have been modified by some hooks
// Remove element from category
if ($id > 0 && $removeelem > 0)
{
	if ($type == Categorie::TYPE_PRODUCT && ($user->rights->produit->creer || $user->rights->service->creer))
	{
		require_once DOL_DOCUMENT_ROOT.'/product/class/product.class.php';
		$tmpobject = new Product($db);
		$result = $tmpobject->fetch($removeelem);
		$elementtype = 'product';
	}
	elseif ($type == Categorie::TYPE_SUPPLIER && $user->rights->societe->creer)
	{
		$tmpobject = new Societe($db);
		$result = $tmpobject->fetch($removeelem);
		$elementtype = 'supplier';
	}
	elseif ($type == Categorie::TYPE_CUSTOMER && $user->rights->societe->creer)
	{
		$tmpobject = new Societe($db);
		$result = $tmpobject->fetch($removeelem);
		$elementtype = 'customer';
	}
	elseif ($type == Categorie::TYPE_MEMBER && $user->rights->adherent->creer)
	{
		require_once DOL_DOCUMENT_ROOT.'/adherents/class/adherent.class.php';
		$tmpobject = new Adherent($db);
		$result = $tmpobject->fetch($removeelem);
		$elementtype = 'member';
	}
	elseif ($type == Categorie::TYPE_CONTACT && $user->rights->societe->creer) {
		require_once DOL_DOCUMENT_ROOT.'/contact/class/contact.class.php';
		$tmpobject = new Contact($db);
		$result = $tmpobject->fetch($removeelem);
		$elementtype = 'contact';
    }
    elseif ($type == Categorie::TYPE_ACCOUNT && $user->rights->banque->configurer)
    {
        require_once DOL_DOCUMENT_ROOT.'/compta/bank/class/account.class.php';
        $tmpobject = new Account($db);
        $result = $tmpobject->fetch($removeelem);
        $elementtype = 'account';
    }
    elseif ($type == Categorie::TYPE_PROJECT && $user->rights->projet->creer)
    {
        require_once DOL_DOCUMENT_ROOT.'/projet/class/project.class.php';
        $tmpobject = new Project($db);
        $result = $tmpobject->fetch($removeelem);
        $elementtype = 'project';
    }

	$result = $object->del_type($tmpobject, $elementtype);
	if ($result < 0) dol_print_error('', $object->error);
}

if ($user->rights->categorie->supprimer && $action == 'confirm_delete' && $confirm == 'yes')
{
	if ($object->delete($user) >= 0)
	{
		header("Location: ".DOL_URL_ROOT.'/categories/index.php?type='.$type);
		exit;
	}
	else
	{
		setEventMessages($object->error, $object->errors, 'errors');
	}
}

if ($type == Categorie::TYPE_PRODUCT && $elemid && $action == 'addintocategory' && ($user->rights->produit->creer || $user->rights->service->creer))
{
	require_once DOL_DOCUMENT_ROOT.'/product/class/product.class.php';
	$newobject = new Product($db);
	$result = $newobject->fetch($elemid);
	$elementtype = 'product';

	// TODO Add into categ
	$result = $object->add_type($newobject, $elementtype);
	if ($result >= 0)
	{
		setEventMessages($langs->trans("WasAddedSuccessfully", $newobject->ref), null, 'mesgs');
	}
	else
	{
		if ($cat->error == 'DB_ERROR_RECORD_ALREADY_EXISTS')
		{
			setEventMessages($langs->trans("ObjectAlreadyLinkedToCategory"), null, 'warnings');
		}
		else
		{
			setEventMessages($object->error, $object->errors, 'errors');
		}
	}
}

// Aplicar descuento masivo
if ($type == Categorie::TYPE_PRODUCT && $action == 'apply_discount' && $user->rights->categorie->apply_massive_discount) {
	$cancel = GETPOST('cancel', 'alpha');

	if (!$cancel) {
		$discount = GETPOST('percent_discount', 'int', '2');

		$date_lim_discount = $date_lim_discountyear ? $date_lim_discountyear . "-" . $date_lim_discountmonth . "-" . $date_lim_discountday : '';
		$current_date = $date_lim_discountyear ? date('Y-m-d') : '';
	
		if ($discount == '') {
			setEventMessage($langs->trans('DiscountRequired'), 'errors');
			$action = 'set_discount';
		} elseif ($discount < 0) {
			setEventMessage('El descuento tiene que tener un valor positivo.', 'errors');
			$action = 'set_discount';
		} elseif (strtotime($date_lim_discount) < strtotime($current_date)) {
			setEventMessage('La fecha de vencimiento del descuento temporal es anterior a la fecha actual.', 'errors');
			$action = 'set_discount';
		} else {
			require_once DOL_DOCUMENT_ROOT . '/product/class/product.class.php';
			$products = $object->getObjectsInCateg("product");

			// Multiplicado de precio
			$decimal = (1 - $discount / 100);
			$success = 0;
			foreach ($products as $product) {
				// Descuento aplicado sobre producto
				if($product->desc_max > 0){
					if ($product->setDiscount($decimal, $date_lim_discountday, $date_lim_discountmonth, $date_lim_discountyear) > 0)
						$success++;
				}
			}
			setEventMessage($langs->trans("RecordsSaved", $success), $success > 0 ? 'mesgs' : 'warnings');
			$action = '';
		}
	}
}

if ($type == Categorie::TYPE_PRODUCT && $action == 'apply_incremento' && $user->rights->categorie->apply_massive_increment) {
    $cancel = GETPOST('cancel', 'alpha');

    if (!$cancel) {
        $incremento = GETPOST('percent_incremento', 'int', '2');

        if ($incremento != '') {
			require_once DOL_DOCUMENT_ROOT . '/product/class/product.class.php';
			require_once DOL_DOCUMENT_ROOT . '/fourn/class/fournisseur.product.class.php';
            $products = $object->getObjectsInCateg("product");


            $success = 0;
            $fail = 0;
			$error = "";
            foreach ($products as $product) {

				$prod = new Product($db);
				$prod->fetch($product->id);
				$cost_price = $prod->cost_price;
				$prod->cost_price_sucursal = $cost_price + ($cost_price * ($incremento / 100));
				$res_update = $prod->update($product->id, $user);
				if ($res_update > 0) {
					$success++;
				} else {
					$fail++;
					$error .= $prod->ref . ", ";
				}
            }
			if($fail > 0){
				setEventMessage($langs->trans("No tienen precio de Compra: ". $error),  'errors');
				$action = 'set_ganancia';
			}else{
				setEventMessage($langs->trans("RecordsSaved", $success), $success > 0 ? 'mesgs' : 'succes');
				$action = '';
			}
        }
        else {
            setEventMessage($langs->trans('Incremento Requerio'), 'errors');
            $action = 'set_ganancia';
        }
    }
}

// Cambio de precio masivo
if ($type == Categorie::TYPE_PRODUCT && $action == 'price_change') {
	require_once DOL_DOCUMENT_ROOT.'/product/class/product.class.php';
	$limit2 = GETPOST('limit');
	$page2 = GETPOST('page');
	$products = $object->getObjectsInCateg("product", 0, $limit2-1, $limit2*$page2);
	$imPrice = str_replace(',','',$_POST['price']);
	$imtva = $_POST['tva_tx'];
	$imPrice_base_type = $_POST['price_base_type'];
	$price_sucursal = $_POST['price_sucursal'];
	$x=0;
	foreach ($products as $product) {
		//$imid[$x]= $_POST['idp'][$x];
		$newprod = new Product($db);
		$newprod->fetch($product->id);
		// Precio mínimo de venta de acuerdo al descuento máximo del producto
		$newpricemin = $imPrice[$x] - ($imPrice[$x] * ($newprod->desc_max / 100));
		$newprod->updatePrice($imPrice[$x], $imPrice_base_type[$x],  $user, $imtva[$x], $newpricemin);
		// Barcode
		$newprod->barcode = $_POST['barcode'][$x];
		
		// Actualizar precio de compra por sucursal
		$newprod->cost_price_sucursal = $price_sucursal[$x];

		$newprod->update($newprod->id, $user);
		$x++;
	}
	setEventMessage("Productos actualizados con éxito");
}

if($action == 'remove_discount') {
	require_once DOL_DOCUMENT_ROOT . '/product/class/product.class.php';
	$products = $object->getObjectsInCateg("product");

	$success = 0;
	foreach ($products as $product) {
		if($product->desc_max > 0){
			if ($product->setDiscount(1) > 0)
				$success++;
		}
	}
	setEventMessage($langs->trans("RecordsSaved", $success), $success > 0 ? 'mesgs' : 'warnings');
	$action = '';
}


/*
 * View
 */

$form = new Form($db);
$formproduct = new FormProduct($db);
$formother = new FormOther($db);

$helpurl = '';
llxHeader("", $langs->trans("Categories"), $helpurl);

if ($type == Categorie::TYPE_PRODUCT)       $title = $langs->trans("ProductsCategoryShort");
elseif ($type == Categorie::TYPE_SUPPLIER)  $title = $langs->trans("SuppliersCategoryShort");
elseif ($type == Categorie::TYPE_CUSTOMER)  $title = $langs->trans("CustomersCategoryShort");
elseif ($type == Categorie::TYPE_MEMBER)    $title = $langs->trans("MembersCategoryShort");
elseif ($type == Categorie::TYPE_CONTACT)   $title = $langs->trans("ContactCategoriesShort");
elseif ($type == Categorie::TYPE_ACCOUNT)   $title = $langs->trans("AccountsCategoriesShort");
elseif ($type == Categorie::TYPE_PROJECT)   $title = $langs->trans("ProjectsCategoriesShort");
elseif ($type == Categorie::TYPE_USER)      $title = $langs->trans("UsersCategoriesShort");
else                                        $title = $langs->trans("Category");

$head = categories_prepare_head($object, $type);


dol_fiche_head($head, 'card', $title, -1, 'category');

$linkback = '<a href="'.DOL_URL_ROOT.'/categories/index.php?leftmenu=cat&type='.$type.'">'.$langs->trans("BackToList").'</a>';
$object->next_prev_filter=" type = ".$object->type;
$object->ref = $object->label;
$morehtmlref='<br><div class="refidno"><a href="'.DOL_URL_ROOT.'/categories/index.php?leftmenu=cat&type='.$type.'">'.$langs->trans("Root").'</a> >> ';
$ways = $object->print_all_ways(" &gt;&gt; ", '', 1);
foreach ($ways as $way)
{
    $morehtmlref.=$way."<br>\n";
}
$morehtmlref.='</div>';

dol_banner_tab($object, 'label', $linkback, ($user->socid?0:1), 'label', 'label', $morehtmlref, '', 0, '', '', 1);


/*
 * Confirmation suppression
 */

if ($action == 'delete')
{
	print $form->formconfirm($_SERVER["PHP_SELF"].'?id='.$object->id.'&amp;type='.$type, $langs->trans('DeleteCategory'), $langs->trans('ConfirmDeleteCategory'), 'confirm_delete', '', '', 1);
}

print '<br>';

print '<div class="fichecenter">';
print '<div class="underbanner clearboth"></div>';
print '<table width="100%" class="border">';

// Description
print '<tr><td class="titlefield notopnoleft tdtop">';
print $langs->trans("Description").'</td><td>';
print dol_htmlentitiesbr($object->description);
print '</td></tr>';

// Color
print '<tr><td class="notopnoleft">';
print $langs->trans("Color").'</td><td>';
print $formother->showColor($object->color);
print '</td></tr>';

if ($type == Categorie::TYPE_PRODUCT) {
	print '<tr><td class="notopnoleft">';
	print $langs->trans("CatSamePrice").'</td><td>';
	print $langs->trans($object->samePrice ? 'Yes' : 'No');
	print '</td></tr>';
}

// Other attributes
include DOL_DOCUMENT_ROOT.'/core/tpl/extrafields_view.tpl.php';

print '</table>';
print '</div>';

dol_fiche_end();

if ($action != 'set_discount') {
	/*
	 * Boutons actions
	 */
	
	print "<div class='tabsAction'>\n";
	
	if ($type == Categorie::TYPE_PRODUCT) {
		if ($user->rights->categorie->apply_massive_discount)
			print "<a class='butAction' href='".DOL_URL_ROOT."/categories/viewcat.php?action=remove_discount&amp;id=".$object->id."&amp;type=".$type."'>".$langs->trans("MassiveDiscountRemove")."</a>";
		else
		print "<a class='butActionRefused' href='#'>".$langs->trans("MassiveDiscountRemove")."</a>";
	}

	if ($type == Categorie::TYPE_PRODUCT) {
		if ($user->rights->categorie->apply_massive_discount)
			print "<a class='butAction' href='".DOL_URL_ROOT."/categories/viewcat.php?action=set_discount&amp;id=".$object->id."&amp;type=".$type."'>".$langs->trans("MassiveDiscount")."</a>";
		else
		print "<a class='butActionRefused' href='#'>".$langs->trans("MassiveDiscount")."</a>";
	}

	 if ($type == Categorie::TYPE_PRODUCT) {
        if ($user->rights->categorie->apply_massive_increment)
            print "<a class='butAction' href='".DOL_URL_ROOT."/categories/viewcat.php?action=set_ganancia&amp;id=".$object->id."&amp;type=".$type."'>".$langs->trans("Aumento precio sucursal")."</a>";
        else
            print "<a class='butActionRefused' href='#'>".$langs->trans("Aumento precio sucursal")."</a>";
    }
	
	if ($user->rights->categorie->creer)
	{
		$socid = ($object->socid ? "&amp;socid=".$object->socid : "");
		print "<a class='butAction' href='edit.php?id=".$object->id.$socid."&amp;type=".$type."'>".$langs->trans("Modify")."</a>";
	}
	
	if ($user->rights->categorie->supprimer)
	{
		print "<a class='butActionDelete' href='".DOL_URL_ROOT."/categories/viewcat.php?action=delete&amp;id=".$object->id."&amp;type=".$type."'>".$langs->trans("Delete")."</a>";
	}
	
	print "</div>";
}



$cats = $object->get_filles();
if ($cats < 0)
{
	dol_print_error($db, $cats->error, $cats->errors);
}
elseif($action != 'set_discount')
{
	print "<br>";
	print "<table class='noborder' width='100%'>\n";
	print "<tr class='liste_titre'><td colspan='2'>".$langs->trans("SubCats").'</td><td class="right">';
	if ($user->rights->categorie->creer)
	{
		print "<a href='".DOL_URL_ROOT."/categories/card.php?action=create&amp;catorigin=".$object->id."&amp;socid=".$object->socid."&amp;type=".$type."&amp;urlfrom=".urlencode($_SERVER["PHP_SELF"].'?id='.$object->id.'&type='.$type)."'>";
		print img_picto($langs->trans("Create"), 'filenew');
		print "</a>";
	}
	print "</td>";
	print "</tr>\n";
	if (count($cats) > 0)
	{
		foreach ($cats as $cat)
		{
			print "\t".'<tr class="oddeven">'."\n";
			print "\t\t".'<td class="nowrap">';
			print "<a href='viewcat.php?id=".$cat->id."&amp;type=".$type."'>".$cat->label."</a>";
			print "</td>\n";
			print "\t\t".'<td colspan="2">'.$cat->description."</td>\n";

			/*
			if ($cat->visible == 1)
			{
				print "\t\t<td>".$langs->trans("ContentsVisibleByAllShort")."</td>\n";
			}
			else
			{
				print "\t\t<td>".$langs->trans("ContentsNotVisibleByAllShort")."</td>\n";
			}
			*/

			print "\t</tr>\n";
		}
	}
	else
	{
		print '<tr class="oddeven"><td colspan="3" class="opacitymedium">'.$langs->trans("NoSubCat").'</td></tr>';
	}
	print "</table>\n";
}


// List of mass actions available
$arrayofmassactions = array(
	//'validate'=>$langs->trans("Validate"),
	//'generate_doc'=>$langs->trans("ReGeneratePDF"),
	//'builddoc'=>$langs->trans("PDFMerge"),
	//'presend'=>$langs->trans("SendByMail"),
);
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);


// List of products or services (type is type of category)
if ($type == Categorie::TYPE_PRODUCT)
{
	$prods = $object->getObjectsInCateg("product", 0, $limit, $offset);
	if ($prods < 0)
	{
		dol_print_error($db, $prods->error, $prods->errors);
	}
	else
	{
		$showclassifyform = 1; $typeid = Categorie::TYPE_PRODUCT;

		// Form to add record into a category
		if ($showclassifyform && $action != 'set_discount' )
		{
			print '<br>';
			print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
			print '<input type="hidden" name="token" value="'.newToken().'">';
			print '<input type="hidden" name="typeid" value="'.$typeid.'">';
			print '<input type="hidden" name="type" value="'.$typeid.'">';
			print '<input type="hidden" name="id" value="'.$object->id.'">';
			print '<input type="hidden" name="action" value="addintocategory">';
			print '<table class="noborder centpercent">';
			print '<tr class="liste_titre"><td>';
			print $langs->trans("AddProductServiceIntoCategory").' &nbsp;';
			$form->select_produits('', 'elemid', '', 0, 0, -1, 2, '', 1);
			print '<input type="submit" class="button" value="'.$langs->trans("ClassifyInCategory").'"></td>';
			print '</tr>';
			print '</table>';
			print '</form>';
		}

        if($action == 'set_ganancia') {
            print load_fiche_titre($langs->trans('Aumento de precio sucursal'), '', '');

            print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
            print '<input type="hidden" name="token" value="'.newToken().'">';
            print '<input type="hidden" name="typeid" value="'.$typeid.'">';
            print '<input type="hidden" name="type" value="'.$typeid.'">';
            print '<input type="hidden" name="id" value="'.$object->id.'">';
            print '<input type="hidden" name="action" value="apply_incremento">';

            print '<table class="noborder centpercent">';
            print '<tr class="liste_titre"><td>';
            print $langs->trans("Percent").' &nbsp;';
            print '<input type="text" name="percent_incremento">';
            print '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp';
            print '<input type="submit" class="button" value="'.$langs->trans("Aplicar aumento").'">';
            print '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp';
            print '<input type="submit" class="button" name="cancel" value="'.$langs->trans("Cancel").'"></td>';
            print '</tr>';
            print '</table>';
            print '</form>';
        }

		if($action == 'set_discount') {
			print '<form method="post" action="'.$_SERVER["PHP_SELF"].'" style="width: 50%; margin: 0 auto;">';
			print '<input type="hidden" name="token" value="'.newToken().'">';
			print '<input type="hidden" name="typeid" value="'.$typeid.'">';
			print '<input type="hidden" name="type" value="'.$typeid.'">';
			print '<input type="hidden" name="id" value="'.$object->id.'">';
			print '<input type="hidden" name="action" value="apply_discount">';

			print '<table class="center noborder">';
			print '<tr class="liste_titre">';
			print '<td colspan="10">'.$langs->trans("MassiveDiscount").'</td>';
			print '</tr>';
			print '<tr>';
			print '<td class="minwidth200">'.$langs->trans("Percent").': </td>';
			print '<td><input type="text" name="percent_discount"></td>';
			print '<td><input type="checkbox" name="show_temporal_discount" id="show_temporal_discount" onchange="toggleDate()"> ' . $langs->trans("TemporalDiscount") . '</td>';
			print '</tr>';
			print '<tr id="date_select_lim_discount" style="display: none;">';
			print '<td><label for="temporal_discount">Fecha límite de descuento:</label></td>';
			print '<td>'.$form->selectDate(-1, 'date_lim_discount').'</td>';
			print '<td></td>';
			print '</tr>';
			print '</table>';
			print '<div class="center">';
			print '<input type="submit" class="button" value="'.$langs->trans("ApplyDiscount").'">';
			print '<input type="submit" class="button" name="cancel" value="'.$langs->trans("Cancel").'">';
			print '</div>';
			print '</form>';

			// Mostrar select para fecha limite si el descuento es temporal
			print '<script>';
			print 'function toggleDate() {';
			print '    var checboxLimitDiscount = document.getElementById("show_temporal_discount");';
			print '    var dateSelectLimitDiscount = document.getElementById("date_select_lim_discount");';
			print '    if (checboxLimitDiscount.checked) {';
			print '        dateSelectLimitDiscount.style.display = "table-row";';
			print '    } else {';
			print '        dateSelectLimitDiscount.style.display = "none";';
			print '    }';
			print '}';
			print '</script>';
		}

		print '<div class="tabsAction right">';
		print '<a id="printTagsButton" class="butAction" onclick="return printTags();" href="' . $_SERVER["PHP_SELF"] . '?id=' . $object->id . '">Imprimir Etiquetas</a>';
		print '</div>';
		print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="typeid" value="'.$typeid.'">';
		print '<input type="hidden" name="type" value="'.$typeid.'">';
		print '<input type="hidden" name="id" value="'.$object->id.'">';
		print '<input type="hidden" name="action" value="'.($action == 'set_discount' ? $action : "list").'">';

		print '<br>';
		$param = '&limit='.$limit.'&id='.$id.'&type='.$type; $num = count($prods); $nbtotalofrecords = ''; $newcardbutton = '';
		print_barre_liste($langs->trans("ProductsAndServices"), $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, '', 0, $newcardbutton, '', $limit);
		print '</form>'."\n";

		print '<span style="color:#017179; font-size: 14px;">Nota: Los precios de compra CEDIS y Sucursal son precios unitarios sin IVA.</span>';

		// Form para el cambio de precio
		print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="limit" value="'.$limit.'">';
		print '<input type="hidden" name="page" value="'.$page.'">';
		print '<input type="hidden" name="typeid" value="'.$typeid.'">';
		print '<input type="hidden" name="type" value="'.$typeid.'">';
		print '<input type="hidden" name="id" value="'.$object->id.'">';
		// print '<input type="hidden" name="action" value="price_change">';
		print "<table class='noborder' width='100%'>\n";
		print '<tr class="liste_titre">';
		print '<th><input type="checkbox" name="checkAll" id="checkAll"></th>';
		print '<th>'.$langs->trans("Ref").'</th>';
		print '<th>'.$langs->trans("Barcode").'</th>';
		print '<th>'.$langs->trans("Tasa de impuesto por defecto").'</th>';
		print '<th>' . $langs->trans("Precio base") . '</th>';
		print '<th>' . $langs->trans("Precio de venta") . '</th>';
		print '<th>' . $langs->trans("Precio de compra CEDIS") . '</th>';
		print '<th>' . $langs->trans("Precio de compra Sucursal") . '</th>';
		print '<th>' . $langs->trans("TemporalDiscount") . '</th>';
		print '<th>' . $langs->trans("DiscountDeadline") . '</th>';
		print '<th>' . $formproduct->selectWarehouses(GETPOST('idwarehouse'), "idwarehouse", '', 1, 0, 0, "ALMACEN") . $form->showFilterButtons() . '</th>';
		print '</tr>';

		if (count($prods) > 0)
		{
			$i = 0;
			foreach ($prods as $prod)
			{
				$i++;
				if ($i > $limit) break;
				//print '<input type="hidden" name="idp[]" value="'.$prod->id.'">';
				print "\t".'<tr class="oddeven">'."\n";
				print '<td></td>';
				// Product code
				print '<td class="nowrap" valign="top">';
				print $prod->getNomUrl(1);
				print "</td>\n";

				// Barcode
				print '<td><input name="barcode[]" id="barcode' . $i . '" value="' . $prod->barcode . '"></td>';

				// Tva
				print '<td>';
				print '<div class="center">';
				print '<select class="flat center" name="tva_tx[]">';
				if($prod->tva_tx == 16){
					print '<option class="left" value="0">0%</option>'; 
					print '<option class="left" value="10">10%</option>'; 
					print '<option class="left" value="16"selected>16%</option>'; 
				}else{
					if ($prod->tva_tx == 10) {
						print '<option class="left" value="0">0%</option>'; 
						print '<option class="left" value="10" selected>10%</option>'; 
						print '<option class="left" value="16">16%</option>';
					} else {
						print '<option class="left" value="0" selected>0%</option>'; 
						print '<option class="left" value="10">10%</option>'; 
						print '<option class="left" value="16">16%</option>';
					}
				}
                print '</select>';
				print '</div>';
				print '</td>';


				// Price base type
				print '<td>';
				print '<div class="center">';
				print '<select class="flat" name="price_base_type[]">';
				if($prod->price_base_type == 'TTC'){
					print '<option class="left" value="HT">Sin IVA</option>'; 
					print '<option class="left" value="TTC" selected>IVA incluido</option>'; 
				}else{
					print '<option class="left" value="HT" selected>Sin IVA</option>'; 
					print '<option class="left" value="TTC">IVA incluido</option>'; 
				}
                print '</select>';
				print '</div>';	
				print '</td>';

				// Price
				print '<td>';
				if ($prod->price_base_type == 'TTC') {
					print '<input type="text" name="price[]" id="price' . $i . '" value="' . price($prod->price_ttc) . '" style="width:70px;">';
				} else {
					print '<input type="text" name="price[]" id="price' . $i . '" value="' . price($prod->price) . '">';
				}				
				print '</td>';

				// Precio de compra CEDIS
				print '<td>';
				$product = new Product($db);
				$product->fetch($prod->id);
				print "$".price($product->cost_price);
				print '</td>';

				unset($product);
				// Precio de compra Sucursal
				print '<td>';
				$product = new Product($db);
				$product->fetch($prod->id);
				print '<input type="text" name="price_sucursal[]" id="price_sucursal' . $i . '" value="' . price($product->cost_price_sucursal) . '">';
				print '</td>';
				unset($product);


				// Temporal discount
				print '<td class="center">';
				if (!empty($prod->temp_discount)) {
					print $prod->temp_discount.'%';
				} else {
					print '0';
				}
				print '</td>';

				// Discount date
				print '<td>';
				if (!empty($prod->date_lim_discount)) {
					print dol_print_date($prod->date_lim_discount, "day");
				}				
				print '</td>';

				// Link to delete from category
				print '<td class="right">';
				$permission = 0;
				if ($type == Categorie::TYPE_PRODUCT)     $permission = ($user->rights->produit->creer || $user->rights->service->creer);
				if ($type == Categorie::TYPE_SUPPLIER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_CUSTOMER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_MEMBER)      $permission = $user->rights->adherent->creer;
				if ($type == Categorie::TYPE_PROJECT)     $permission = $user->rights->projet->creer;
				if ($permission)
				{
					print "<a href= '".$_SERVER['PHP_SELF']."?".(empty($socid) ? 'id' : 'socid')."=".$object->id."&amp;type=".$typeid."&amp;removeelem=".$prod->id."'>";
					print $langs->trans("DeleteFromCat");
					print img_picto($langs->trans("DeleteFromCat"), 'unlink');
					print "</a>";
				}
				print "</tr>\n";

				$idwarehouse = GETPOST('idwarehouse', 'int');

				$sql = "SELECT pb.batch, pb.qty, ps.fk_product, ps.fk_entrepot, pl.rowid as lotid FROM " . MAIN_DB_PREFIX . "product_batch pb INNER JOIN " . MAIN_DB_PREFIX . "product_stock ps ON pb.fk_product_stock = ps.rowid";
				$sql .= " LEFT JOIN llx_product_lot pl ON pl.fk_product = ps.fk_product AND pl.batch = pb.batch AND pl.eatby = pb.eatby AND pl.sellby = pb.sellby"; 
				$sql .= " WHERE ps.fk_product = " . $prod->id . " AND pb.qty <> 0";
				if ($idwarehouse >= -1) $sql .= " AND ps.fk_entrepot = " . $idwarehouse;
				$sql .= " ORDER BY ps.fk_entrepot DESC";
				$resql = $db->query($sql);

				if ($resql->num_rows > 0) {
					$entrepot = new Entrepot($db);
					$product_lot_static = new Productlot($db);
					$total = 0;
				
					print '<tr class="oddeven">';
					print '<td></td>';
					print '<td colspan="6" class="nowrap right" valign="top"><b>Lote</td>';
					print '<td class="nowrap" valign="top"><b>Cantidad</td>';
					print '<td class="nowrap" valign="top"><b>Almacén</td>';
				
					while ($obj = $db->fetch_object($resql)) {
						$entrepot->fetch($obj->fk_entrepot);
						$product_lot_static->id = $obj->lotid;
						$product_lot_static->batch = $obj->batch;
				
						print '<tr class="oddeven">';
						print "<td class=\"left\"><input type=\"checkbox\" class=\"chkInd\" name=\"{$prod->id}_{$obj->qty}_{$obj->lotid}_{$entrepot->id}\" value=\"{$prod->id}\"></td>";
						print '<td colspan="6" class="nowrap right" valign="top">' . $product_lot_static->getNomUrl(1) . '</td>';
						print "<td class=\"nowrap\" valign=\"top\">{$obj->qty}</td>";
						print '<td class="nowrap" valign="top">' . $entrepot->getNomUrl(1) . '</td>';
						print '</tr>';
						$total += $obj->qty;
					}
					print "<tr class=\"oddeven\"><td colspan=\"7\" class=\"nowrap right\" valign=\"top\"><b>Total</td><td class=\"nowrap\" valign=\"top\"><b>$total</td><td></td>";
				}

			}
			print "</table>\n";
			// Script para pasar al siguiente campo con la tecla Enter
			?>
			<script>
			let inputs = document.querySelectorAll("input[id^=price]");
			let inputs2 = document.querySelectorAll("input[id^=barcode]");

			inputs.forEach(input => input.addEventListener("keypress", nextFocus));
			inputs2.forEach(input => input.addEventListener("keypress", nextFocus2));
			function nextFocus(e) {
				if (e.keyCode == 13) {
					let actual = parseInt(e.target.id.replace("price", ""));
					// Solo si no es el último
					if (actual < inputs.length) {
						// Evitar comportamiento normal del evento
						e.preventDefault();
						// Activar siguiente campo
						inputs[actual].focus();
					}
				}
			}

			function nextFocus2(e) {
				if (e.keyCode == 13) {
					let actual = parseInt(e.target.id.replace("barcode", ""));
					// Solo si no es el último
					if (actual < inputs.length) {
						// Evitar comportamiento normal del evento
						e.preventDefault();
						// Activar siguiente campo
						inputs2[actual].focus();
					}
				}
			}
			var ajaxCounter = 0;
			$(document).ready(function () {

				$("#checkAll").click(function () {
					let isChecked = false;
					if ($(this).is(":checked")) {
						isChecked = true;
					}

					$(".chkInd").each(function (i, e) {
						if (isChecked) {
							$(e).prop("checked", !isChecked);
							$(e).change();
						} else {
							$("#confirmButton").hide();
						}
						if (!$(e).prop("disabled")) {
							$(e).prop("checked", isChecked);
							$(e).change();
						}
					});
				});

				$(".chkInd").change(function () {
					const fk_product = $(this).attr("name").split("_")[0];
					const qty = $(this).attr("name").split("_")[1];
					const batch = $(this).attr("name").split("_")[2];
					const warehouse = $(this).attr("name").split("_")[3];
					const tableTags = $("#tableTags");
					if ($(this).is(":checked")) {
						$.ajax({
							method: "POST",
							url: "ajaxProdURL.php",
							data: {
								fk_product: fk_product,
								qty: qty,
								batch: batch,
								warehouse: warehouse,
							},
						}).done(function (msg) {
							tableTags.append(msg);
							ajaxCounter++;

							// Verificar si todas las solicitudes Ajax se han completado
							if (ajaxCounter === $(".chkInd:checked").length) {
								$("#confirmButton").show();
							}
						});
					} else {
						if (ajaxCounter > 0) ajaxCounter--;
						// Verificar si todas las solicitudes Ajax se han completado
						if ($(".chkInd:checked").length === 0) {
							$("#confirmButton").hide();
						}
						//Se eliminan las filas cuando se quita el check
						tableTags.find("tr").each(function (i, e) {
							if ($(e).attr("name") == fk_product + "_" + qty + "_" + batch) {
								$(e).remove();
							}
						});
					}
				});

				$("#idwarehouse").change(function () {
					console.log($("#idwarehouse").val());
				});
			});

			function printTags() {
				$("#printTags_line_dialog").dialog({
					autoOpen: false,
					width: 800,
					height: 400,
					buttons: [
						{
							text: "Confirmar",
							id: "confirmButton",
							click: function () {

								//Send Tags									
								let l = "<?php DOL_URL_ROOT ?>/categories/pdf_tags.php";
								let tags = "";
								$("#tableTags tr").each(function (i, e) {
									if (i > 0) {
										const fk_prod = $(e).attr("name").split('_')[0];
										const qty = $(e).attr("name").split('_')[1];
										const batch = $(e).attr("name").split('_')[2];
										tags += fk_prod + '_' + qty + '_' + batch + ',';
									}
								});
								l += "?tags=" + tags;

								Object.assign(document.createElement('a'), { target: '_blank', href: l }).click();
							}
						},
						{
							text: "Cancelar",
							click: function () {
								$(this).dialog("close");
							}
						}
					],
					open: function (event, ui) {
						// Deshabilitar el botón de Confirmar al abrir el diálogo si las peticiones ajax no han finalizado
						if (ajaxCounter == 0 || ajaxCounter < $(".chkInd:checked").length) {
							$("#confirmButton").hide();
						}
					},
					close: function (event, ui) {
						location.reload();
					}
				});

				$("#printTags_line_dialog").dialog("open");
				return false;
			}
			</script>
			<?php
			print '<div class="right">';
			print '<button type="submit" name="action" class="button" value="price_change">' . $langs->trans("Save") . '</button>';
			print '</div>';
		}
		else
		{
			print '<tr class="oddeven"><td colspan="2" class="opacitymedium">'.$langs->trans("ThisCategoryHasNoProduct").'</td></tr>';
			print "</table>\n";
		}		
		print '</form>'."\n";
		
	}
}

if ($type == Categorie::TYPE_SUPPLIER)
{
	$socs = $object->getObjectsInCateg("supplier", 0, $limit, $offset);
	if ($socs < 0)
	{
		dol_print_error($db, $socs->error, $socs->errors);
	}
	else
	{
		print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="typeid" value="'.$typeid.'">';
		print '<input type="hidden" name="type" value="'.$typeid.'">';
		print '<input type="hidden" name="id" value="'.$object->id.'">';
		print '<input type="hidden" name="action" value="list">';

		print '<br>';
		$param = '&limit='.$limit.'&id='.$id.'&type='.$type; $num = count($socs); $nbtotalofrecords = ''; $newcardbutton = '';
		print_barre_liste($langs->trans("Suppliers"), $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, '', 0, $newcardbutton, '', $limit);

		print '<table class="noborder centpercent">'."\n";
		print '<tr class="liste_titre"><td colspan="2">'.$langs->trans("Name")."</td></tr>\n";

		if (count($socs) > 0)
		{
			$i = 0;
			foreach ($socs as $soc)
			{
				$i++;
				if ($i > $limit) break;

				print "\t".'<tr class="oddeven">'."\n";
				print '<td class="nowrap" valign="top">';
				print $soc->getNomUrl(1);
				print "</td>\n";
				// Link to delete from category
				print '<td class="right">';
				$permission = 0;
				if ($type == Categorie::TYPE_PRODUCT)     $permission = ($user->rights->produit->creer || $user->rights->service->creer);
				if ($type == Categorie::TYPE_SUPPLIER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_CUSTOMER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_MEMBER)      $permission = $user->rights->adherent->creer;
				if ($type == Categorie::TYPE_PROJECT)     $permission = $user->rights->projet->creer;
				if ($permission)
				{
					print "<a href= '".$_SERVER['PHP_SELF']."?".(empty($socid) ? 'id' : 'socid')."=".$object->id."&amp;type=".$typeid."&amp;removeelem=".$soc->id."'>";
					print $langs->trans("DeleteFromCat");
					print img_picto($langs->trans("DeleteFromCat"), 'unlink');
					print "</a>";
				}
				print '</td>';

				print "</tr>\n";
			}
		}
		else
		{
			print '<tr class="oddeven"><td class="opacitymedium">'.$langs->trans("ThisCategoryHasNoSupplier").'</td></tr>';
		}
		print "</table>\n";

		print '</form>'."\n";
	}
}

if ($type == Categorie::TYPE_CUSTOMER)
{
	$socs = $object->getObjectsInCateg("customer", 0, $limit, $offset);
	if ($socs < 0)
	{
		dol_print_error($db, $socs->error, $socs->errors);
	}
	else
	{
		print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="typeid" value="'.$typeid.'">';
		print '<input type="hidden" name="type" value="'.$typeid.'">';
		print '<input type="hidden" name="id" value="'.$object->id.'">';
		print '<input type="hidden" name="action" value="list">';

		print '<br>';
		$param = '&limit='.$limit.'&id='.$id.'&type='.$type; $num = count($socs); $nbtotalofrecords = ''; $newcardbutton = '';
		print_barre_liste($langs->trans("Customers"), $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, '', 0, $newcardbutton, '', $limit);

		print '<table class="noborder centpercent">'."\n";
		print '<tr class="liste_titre"><td colspan="2">'.$langs->trans("Name").'</td></tr>'."\n";

		if (count($socs) > 0)
		{
			$i = 0;
			foreach ($socs as $key => $soc)
			{
				$i++;
				if ($i > $limit) break;

				print "\t".'<tr class="oddeven">'."\n";
				print '<td class="nowrap" valign="top">';
				print $soc->getNomUrl(1);
				print "</td>\n";
				// Link to delete from category
				print '<td class="right">';
				$permission = 0;
				if ($type == Categorie::TYPE_PRODUCT)     $permission = ($user->rights->produit->creer || $user->rights->service->creer);
				if ($type == Categorie::TYPE_SUPPLIER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_CUSTOMER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_MEMBER)      $permission = $user->rights->adherent->creer;
				if ($type == Categorie::TYPE_PROJECT)     $permission = $user->rights->projet->creer;
				if ($permission)
				{
					print "<a href= '".$_SERVER['PHP_SELF']."?".(empty($socid) ? 'id' : 'socid')."=".$object->id."&amp;type=".$typeid."&amp;removeelem=".$soc->id."'>";
					print $langs->trans("DeleteFromCat");
					print img_picto($langs->trans("DeleteFromCat"), 'unlink');
					print "</a>";
				}
				print '</td>';
				print "</tr>\n";
			}
		}
		else
		{
			print '<tr class="oddeven"><td class="opacitymedium">'.$langs->trans("ThisCategoryHasNoCustomer").'</td></tr>';
		}
		print "</table>\n";

		print '</form>'."\n";
	}
}

// List of members
if ($type == Categorie::TYPE_MEMBER)
{
	require_once DOL_DOCUMENT_ROOT.'/adherents/class/adherent.class.php';

	$prods = $object->getObjectsInCateg("member", 0, $limit, $offset);
	if ($prods < 0)
	{
		dol_print_error($db, $prods->error, $prods->errors);
	}
	else
	{
		print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="typeid" value="'.$typeid.'">';
		print '<input type="hidden" name="type" value="'.$typeid.'">';
		print '<input type="hidden" name="id" value="'.$object->id.'">';
		print '<input type="hidden" name="action" value="list">';

		print '<br>';
		$param = '&limit='.$limit.'&id='.$id.'&type='.$type; $num = count($prods); $nbtotalofrecords = ''; $newcardbutton = '';
		print_barre_liste($langs->trans("Member"), $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, '', 0, $newcardbutton, '', $limit);

		print "<table class='noborder' width='100%'>\n";
		print '<tr class="liste_titre"><td colspan="4">'.$langs->trans("Name").'</td></tr>'."\n";

		if (count($prods) > 0)
		{
			$i = 0;
			foreach ($prods as $key => $member)
			{
				$i++;
				if ($i > $limit) break;

				print "\t".'<tr class="oddeven">'."\n";
				print '<td class="nowrap" valign="top">';
				$member->ref = $member->login;
				print $member->getNomUrl(1, 0);
				print "</td>\n";
				print '<td class="tdtop">'.$member->lastname."</td>\n";
				print '<td class="tdtop">'.$member->firstname."</td>\n";
				// Link to delete from category
				print '<td class="right">';
				$permission = 0;
				if ($type == Categorie::TYPE_PRODUCT)     $permission = ($user->rights->produit->creer || $user->rights->service->creer);
				if ($type == Categorie::TYPE_SUPPLIER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_CUSTOMER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_MEMBER)      $permission = $user->rights->adherent->creer;
				if ($type == Categorie::TYPE_PROJECT)     $permission = $user->rights->projet->creer;
				if ($permission)
				{
					print "<a href= '".$_SERVER['PHP_SELF']."?".(empty($socid) ? 'id' : 'socid')."=".$object->id."&amp;type=".$typeid."&amp;removeelem=".$member->id."'>";
					print $langs->trans("DeleteFromCat");
					print img_picto($langs->trans("DeleteFromCat"), 'unlink');
					print "</a>";
				}
				print "</tr>\n";
			}
		}
		else
		{
			print '<tr class="oddeven"><td colspan="3" class="opacitymedium">'.$langs->trans("ThisCategoryHasNoMember").'</td></tr>';
		}
		print "</table>\n";

		print '</form>'."\n";
	}
}

// Categorie contact
if ($type == Categorie::TYPE_CONTACT)
{
	$contacts = $object->getObjectsInCateg("contact", 0, $limit, $offset);
	if ($contacts < 0)
	{
		dol_print_error($db, $contacts->error, $contacts->errors);
	}
	else
	{
		print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="typeid" value="'.$typeid.'">';
		print '<input type="hidden" name="type" value="'.$typeid.'">';
		print '<input type="hidden" name="id" value="'.$object->id.'">';
		print '<input type="hidden" name="action" value="list">';

		print '<br>';
		$param = '&limit='.$limit.'&id='.$id.'&type='.$type; $num = count($contacts); $nbtotalofrecords = ''; $newcardbutton = '';
		print_barre_liste($langs->trans("Contact"), $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, '', 0, $newcardbutton, '', $limit);

		print '<table class="noborder centpercent">'."\n";
		print '<tr class="liste_titre"><td colspan="2">'.$langs->trans("Ref").'</td></tr>'."\n";

		if (count($contacts) > 0)
		{
			$i = 0;
			foreach ($contacts as $key => $contact)
			{
				$i++;
				if ($i > $limit) break;

				print "\t".'<tr class="oddeven">'."\n";
				print '<td class="nowrap" valign="top">';
				print $contact->getNomUrl(1, 'category');
				print "</td>\n";
				// Link to delete from category
				print '<td class="right">';
				$permission = 0;
				if ($type == Categorie::TYPE_PRODUCT)     $permission = ($user->rights->produit->creer || $user->rights->service->creer);
				if ($type == Categorie::TYPE_SUPPLIER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_CUSTOMER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_MEMBER)      $permission = $user->rights->adherent->creer;
				if ($type == Categorie::TYPE_PROJECT)     $permission = $user->rights->projet->creer;
				if ($permission)
				{
					print "<a href= '".$_SERVER['PHP_SELF']."?".(empty($socid) ? 'id' : 'socid')."=".$object->id."&amp;type=".$typeid."&amp;removeelem=".$contact->id."'>";
					print $langs->trans("DeleteFromCat");
					print img_picto($langs->trans("DeleteFromCat"), 'unlink');
					print "</a>";
				}
				print '</td>';
				print "</tr>\n";
			}
		}
		else
		{
			print '<tr class="oddeven"><td class="opacitymedium">'.$langs->trans("ThisCategoryHasNoContact").'</td></tr>';
		}
		print "</table>\n";

		print '</form>'."\n";
	}
}

// List of accounts
if ($type == Categorie::TYPE_ACCOUNT)
{
    require_once DOL_DOCUMENT_ROOT.'/compta/bank/class/account.class.php';

    $accounts = $object->getObjectsInCateg("account", 0, $limit, $offset);
    if ($accounts < 0)
    {
        dol_print_error($db, $accounts->error, $accounts->errors);
    }
    else
    {
    	print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
    	print '<input type="hidden" name="token" value="'.newToken().'">';
    	print '<input type="hidden" name="typeid" value="'.$typeid.'">';
    	print '<input type="hidden" name="type" value="'.$typeid.'">';
    	print '<input type="hidden" name="id" value="'.$object->id.'">';
    	print '<input type="hidden" name="action" value="list">';

    	print '<br>';
    	$param = '&limit='.$limit.'&id='.$id.'&type='.$type; $num = count($accounts); $nbtotalofrecords = ''; $newcardbutton = '';
    	print_barre_liste($langs->trans("Account"), $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, '', 0, $newcardbutton, '', $limit);

    	print "<table class='noborder' width='100%'>\n";
        print '<tr class="liste_titre"><td colspan="4">'.$langs->trans("Ref").'</td></tr>'."\n";

        if (count($accounts) > 0)
        {
        	$i = 0;
            foreach ($accounts as $key => $account)
            {
            	$i++;
            	if ($i > $limit) break;

                print "\t".'<tr class="oddeven">'."\n";
                print '<td class="nowrap" valign="top">';
                print $account->getNomUrl(1, 0);
                print "</td>\n";
                print '<td class="tdtop">'.$account->bank."</td>\n";
                print '<td class="tdtop">'.$account->number."</td>\n";
                // Link to delete from category
                print '<td class="right">';
                $permission = 0;
                if ($type == Categorie::TYPE_PRODUCT)     $permission = ($user->rights->produit->creer || $user->rights->service->creer);
                if ($type == Categorie::TYPE_SUPPLIER)    $permission = $user->rights->societe->creer;
                if ($type == Categorie::TYPE_CUSTOMER)    $permission = $user->rights->societe->creer;
                if ($type == Categorie::TYPE_MEMBER)      $permission = $user->rights->adherent->creer;
                if ($type == Categorie::TYPE_PROJECT)     $permission = $user->rights->projet->creer;
                if ($permission)
                {
                    print "<a href= '".$_SERVER['PHP_SELF']."?".(empty($socid) ? 'id' : 'socid')."=".$object->id."&amp;type=".$typeid."&amp;removeelem=".$account->id."'>";
                    print $langs->trans("DeleteFromCat");
                    print img_picto($langs->trans("DeleteFromCat"), 'unlink');
                    print "</a>";
                }
                print "</tr>\n";
            }
        }
        else
        {
            print '<tr class="oddeven"><td colspan="3" class="opacitymedium">'.$langs->trans("ThisCategoryHasNoAccount").'</td></tr>';
        }
        print "</table>\n";

        print '</form>'."\n";
    }
}

// List of Project
if ($type == Categorie::TYPE_PROJECT)
{
	require_once DOL_DOCUMENT_ROOT.'/projet/class/project.class.php';

	$projects = $object->getObjectsInCateg("project", 0, $limit, $offset);
	if ($projects < 0)
	{
		dol_print_error($db, $object->error, $object->errors);
	}
	else
	{
		print '<form method="post" action="'.$_SERVER["PHP_SELF"].'">';
		print '<input type="hidden" name="token" value="'.newToken().'">';
		print '<input type="hidden" name="typeid" value="'.$typeid.'">';
		print '<input type="hidden" name="type" value="'.$typeid.'">';
		print '<input type="hidden" name="id" value="'.$object->id.'">';
		print '<input type="hidden" name="action" value="list">';

		print '<br>';
		$param = '&limit='.$limit.'&id='.$id.'&type='.$type; $num = count($projects); $nbtotalofrecords = ''; $newcardbutton = '';
		print_barre_liste($langs->trans("Project"), $page, $_SERVER["PHP_SELF"], $param, $sortfield, $sortorder, $massactionbutton, $num, $nbtotalofrecords, '', 0, $newcardbutton, '', $limit);

		print "<table class='noborder' width='100%'>\n";
		print '<tr class="liste_titre"><td colspan="4">'.$langs->trans("Ref").'</td></tr>'."\n";

		if (count($projects) > 0)
		{
			$i = 0;
			foreach ($projects as $key => $project)
			{
				$i++;
				if ($i > $limit) break;

				print "\t".'<tr class="oddeven">'."\n";
				print '<td class="nowrap" valign="top">';
				print $project->getNomUrl(1);
				print "</td>\n";
				print '<td class="tdtop">'.$project->ref."</td>\n";
				print '<td class="tdtop">'.$project->title."</td>\n";
				// Link to delete from category
				print '<td class="right">';
				$permission = 0;
				if ($type == Categorie::TYPE_PRODUCT)     $permission = ($user->rights->produit->creer || $user->rights->service->creer);
				if ($type == Categorie::TYPE_SUPPLIER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_CUSTOMER)    $permission = $user->rights->societe->creer;
				if ($type == Categorie::TYPE_MEMBER)      $permission = $user->rights->adherent->creer;
				if ($type == Categorie::TYPE_PROJECT)     $permission = $user->rights->projet->creer;
				if ($permission)
				{
					print "<a href= '".$_SERVER['PHP_SELF']."?".(empty($socid) ? 'id' : 'socid')."=".$object->id."&amp;type=".$typeid."&amp;removeelem=".$project->id."'>";
					print $langs->trans("DeleteFromCat");
					print img_picto($langs->trans("DeleteFromCat"), 'unlink');
					print "</a>";
				}
				print "</tr>\n";
			}
		}
		else
		{
			print '<tr class="oddeven"><td colspan="3" class="opacitymedium">'.$langs->trans("ThisCategoryHasNoProject").'</td></tr>';
		}
		print "</table>\n";

		print '</form>'."\n";
	}
}

print '<div hidden id="printTags_line_dialog" name="printTags_line_dialog" title="' . $langs->trans("PrintTag") . '">';
print '<p> ¿Desea Confirmar las Cantidades a Imprimir? </p>';
print '<table class="centpercent noborder" id="tableTags" name="tableTags">';
print '<tr class="liste_titre"> <th style="width: 70%;"> Producto </th> <th>Lote</th> <th>ID Lote</th> <th> Etiquetas a Imprimir </th> </tr>';
print '</table>';
print '</div>';

// End of page
llxFooter();
$db->close();
